apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - objectstore.yaml
  - postgres-s3-creds.yaml
  - nextcloud-postgres-secret.yaml
  - nextcloud-admin-secret.yaml
  - nextcloud-redis-secret.yaml
  - scheduled-backup.yaml
  - nextcloud-pg.yaml

namespace: nextcloud

helmCharts:
  - name: nextcloud
    version: 8.7.0
    repo: https://nextcloud.github.io/helm/
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: values.yaml
