apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: sealed-secrets
    version: 2.18.0
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets
    namespace: kubeseal

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
