apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: longhorn
    version: 1.11.0
    repo: https://charts.longhorn.io
    releaseName: lognhorn
    namespace: longhorn-system
    valuesFile: values.yaml
