apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: reloader
    version: 2.2.5
    repo: https://stakater.github.io/stakater-charts
    releaseName: reloader
    namespace: reloader
