apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - objectstore.yaml
  - postres-s3-creds.yaml
  - authentik-env.yaml
  - authentik-db.yaml
  - scheduled-backup.yaml
  - authentik-pg.yaml
  - media-pvc.yaml

namespace: authentik

helmCharts:
  - name: authentik
    version: 2025.12.3
    repo: https://charts.goauthentik.io
    releaseName: auth
    namespace: authentik
    valuesFile: values.yaml
